refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/access.log"
    encoder:
      pattern: "{d} - {m}{n}"
  log_file:
    kind: file
    path: "log/application.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} - {m}{n}"
    
root:
  level: info
  appenders:
    - stdout
loggers:
  requests:
    level: info
    appenders:
      - requests
    additive: false
  actix_web_log4rs:
    level: info
    appenders:
      - log_file
    additive: false